/**
 * FinPilot v0 — Analytics Service.
 *
 * Generates the derived tables (all read-only):
 *   - monthly_analytics : normalized facts per (period × metric × dimension)
 *   - financial_score   : weighted scoring engine (AI-coach ready)
 *   - roadmap           : financial progression engine (stages 1-7)
 *
 * Never hand-edited. Regenerated by trigger or action "analytics.run".
 */

var AnalyticsService = {
  /**
   * Regenerate all analytics for a range of periods (default: current period
   * plus 11 previous months).
   */
  run: function () {
    return withLock(function () {
      var retention = SettingsService.get("analytics_retention_months") || 36;
      var periods = AnalyticsService.lastPeriods(retention);
      AnalyticsService.writeMonthly(periods);
      ScoreService.update();
      RoadmapService.update();
      emit("analytics.updated", { periods: periods });
      return { data: { periods: periods.length, generated_at: isoNow() } };
    });
  },

  lastPeriods: function (n) {
    var out = [];
    var p = monthStamp(new Date());
    for (var i = 0; i < n; i++) {
      out.unshift(p);
      p = prevPeriod(p);
    }
    return out;
  },

  /** Writes all monthly_analytics rows for the given periods. */
  writeMonthly: function (periods) {
    var ledger = readTable("transactions").filter(function (r) {
      return String(r.status).toUpperCase() === "POSTED";
    });
    var accounts = readTable("accounts");
    var categories = readTable("categories");
    var t0 = Date.now();

    // aggregates keyed by period
    var rows = [];
    var addRow = function (period, metric, dimension, rank, value) {
      rows.push([
        IdGenerator.analytics(), period, metric,
        dimension == null ? "" : dimension,
        rank == null ? "" : rank,
        typeof value === "number" ? Math.round(value * 100) / 100 : 0,
        new Date(t0).toISOString()
      ]);
    };

    periods.forEach(function (period) {
      var start = periodStart(period);
      var end = periodEnd(period);
      var inPeriod = ledger.filter(function (t) {
        return String(t.date) >= start && String(t.date) <= end;
      });
      var income = sumWhere(inPeriod, "INCOME");
      var expense = sumWhere(inPeriod, "EXPENSE");
      var transfer = sumWhere(inPeriod, "TRANSFER");

      addRow(period, "INCOME", null, null, income);
      addRow(period, "EXPENSE", null, null, expense);
      addRow(period, "SAVINGS", null, null, income - expense);
      addRow(period, "CASH_FLOW", null, null, income - expense);
      addRow(period, "SAVINGS_RATE", null, null,
        income > 0 ? (income - expense) / income : 0);
      var days = periodDays(period);
      addRow(period, "AVG_DAILY_SPEND", null, null, days > 0 ? expense / days : 0);

      // category analysis (top 8 expense categories)
      AnalyticsService.topBy(inPeriod, "category_id", "CATEGORY_SPEND", period, addRow, 8);

      // merchant analysis (top 8)
      AnalyticsService.topBy(inPeriod, "merchant", "MERCHANT_SPEND", period, addRow, 8);

      // account analysis — balance per account at end of period
      accounts.forEach(function (acc) {
        var balance = AccountBalanceEngine.atDate(acc, ledger, end);
        addRow(period, "ACCOUNT_BALANCE", acc.account_id, null, balance);
      });

      // net worth at end of period
      var netWorth = accounts.reduce(function (sum, acc) {
        return sum + AccountBalanceEngine.atDate(acc, ledger, end);
      }, 0);
      addRow(period, "NET_WORTH", null, null, netWorth);
    });

    // month-over-month trends (labeled on the later month, vs its predecessor)
    var sorted = periods.slice().sort(); // chronological ascending
    for (var i = 1; i < sorted.length; i++) {
      var prev = monthlyTotals(rows, sorted[i - 1]);
      var cur = monthlyTotals(rows, sorted[i]);
      var trend = function (metric) {
        var a = prev[metric] || 0, b = cur[metric] || 0;
        return a !== 0 ? (b - a) / Math.abs(a) : 0;
      };
      addRow(sorted[i], "TREND_INCOME", null, null, trend("INCOME"));
      addRow(sorted[i], "TREND_EXPENSE", null, null, trend("EXPENSE"));
      addRow(sorted[i], "TREND_NET_WORTH", null, null,
        (cur["NET_WORTH"] || 0) - (prev["NET_WORTH"] || 0));
    }

    // rewrite analytics table for these periods (delete old rows for the same periods)
    AnalyticsService.replaceRows(periods, rows);
    return rows.length;
  },

  topBy: function (txns, field, metric, period, addRow, limit) {
    var agg = {};
    txns.forEach(function (t) {
      var key = String(t[field] || "").trim();
      if (!key) return;
      agg[key] = (agg[key] || 0) + Number(t.amount);
    });
    Object.keys(agg)
      .map(function (k) { return { k: k, v: agg[k] }; })
      .sort(function (a, b) { return b.v - a.v; })
      .slice(0, limit)
      .forEach(function (entry, idx) {
        addRow(period, metric, entry.k, idx + 1, entry.v);
      });
  },

  /**
   * Removes analytics rows for the given periods (and anything outside the
   * retention window), then writes the fresh matrix. keep + new rows are
   * written in one call so they can never overlap or corrupt each other.
   */
  replaceRows: function (periods, matrix) {
    var def = TABLES.monthly_analytics;
    var retention = Number(SettingsService.get("analytics_retention_months")) || 36;
    var valid = {};
    AnalyticsService.lastPeriods(retention).forEach(function (p) { valid[p] = true; });
    var keep = readTable("monthly_analytics").filter(function (r) {
      return valid[String(r.period)] && periods.indexOf(String(r.period)) < 0;
    });
    var keepMatrix = keep.map(function (r) {
      return def.cols.map(function (c) {
        var v = r[c];
        return (v === undefined || v === null) ? "" : v;
      });
    });
    clearTableData("monthly_analytics");
    writeTableData("monthly_analytics", keepMatrix.concat(matrix));
  },

  /** Pulls out totals for a period from the in-memory row matrix. */
  apiRun: function () {
    var res = AnalyticsService.run();
    return { data: res.data };
  },

  apiStatus: function () {
    var rows = readTable("monthly_analytics");
    var periods = {};
    rows.forEach(function (r) { periods[r.period] = true; });
    return { data: { periods: Object.keys(periods).sort(), row_count: rows.length } };
  },

  onLedgerChanged: function () {
    // Debounced: scheduled triggers regenerate; here we just mark dirty.
    CacheServiceCache.invalidate();
  }
};

function sumWhere(txns, type) {
  return txns.reduce(function (sum, t) {
    return String(t.type) === type ? sum + Number(t.amount) : sum;
  }, 0);
}

function periodDays(period) {
  var parts = period.split("-");
  var d = new Date(Date.UTC(Number(parts[0]), Number(parts[1]), 0));
  return d.getUTCDate();
}

function monthlyTotals(matrix, period) {
  var out = {};
  matrix.forEach(function (r) {
    if (r[1] === period) out[r[2]] = Number(r[5]);
  });
  return out;
}

/**
 * Account balance at a given date (inclusive). Derived from the ledger only.
 */
var AccountBalanceEngine = {
  atDate: function (account, ledger, dateStampIncl) {
    var bal = Number(account.opening_balance) || 0;
    var id = String(account.account_id);
    for (var i = 0; i < ledger.length; i++) {
      var t = ledger[i];
      if (String(t.status).toUpperCase() !== "POSTED") continue;
      if (String(t.date) > dateStampIncl) continue;
      var type = String(t.type);
      if (type === "INCOME" && String(t.account_id) === id) bal += Number(t.amount);
      else if (type === "EXPENSE" && String(t.account_id) === id) bal -= Number(t.amount);
      else if (type === "TRANSFER") {
        if (String(t.to_account_id) === id) bal += Number(t.amount);
        if (String(t.from_account_id) === id) bal -= Number(t.amount);
      }
    }
    return bal;
  }
};

/** Minimal cache helper (Apps Script CacheService wrapper). */
var CacheServiceCache = {
  invalidate: function () {
    try { CacheService.getScriptCache().removeAll(); } catch (e) { }
  }
};

/**
 * Financial Score — scoring engine.
 * Metrics, weights and targets are configured; current_value is derived;
 * score/status/remarks are generated. Built for future AI coaching.
 */
var ScoreService = {
  METRICS: [
    { code: "SAVINGS_RATE", name: "Savings Rate", weight: 25, target: "savings_rate_target", higherIsBetter: true },
    { code: "EMERGENCY_FUND_MONTHS", name: "Emergency Fund Months", weight: 25, target: "emergency_fund_months_target", higherIsBetter: true },
    { code: "BURN_RATE", name: "Burn Rate (monthly burn vs income)", weight: 15, target: "burn_rate_ratio_target", higherIsBetter: false },
    { code: "DEBT_TO_INCOME", name: "Debt Service to Income", weight: 15, target: "debt_ratio_target", higherIsBetter: false },
    { code: "NET_WORTH_MOMENTUM", name: "Net Worth Momentum (6m growth)", weight: 10, target: "net_worth_growth_target", higherIsBetter: true },
    { code: "EXPENSE_CONTROL", name: "Expense Control (vs budget)", weight: 10, target: "expense_control_target", higherIsBetter: true }
  ],

  update: function () {
    var ledger = readTable("transactions").filter(function (r) {
      return String(r.status).toUpperCase() === "POSTED";
    });
    var analytics = readTable("monthly_analytics");
    var accounts = readTable("accounts");
    var now = new Date();
    var curPeriod = monthStamp(now);
    var burnPeriods = AnalyticsService.lastPeriods(Number(SettingsService.get("burn_rate_months")) || 3);

    var value = function (period, metric) {
      for (var i = 0; i < analytics.length; i++) {
        if (String(analytics[i].period) === period && String(analytics[i].metric) === metric &&
            !analytics[i].dimension) return Number(analytics[i].value);
      }
      return 0;
    };

    // Metric computations
    var income = value(curPeriod, "INCOME");
    var expense = value(curPeriod, "EXPENSE");
    var savingsRate = income > 0 ? (income - expense) / income : 0;

    // emergency fund months = months of avg burn covered by cash/savings balance
    var burn3 = avgBurn(analytics, burnPeriods);
    var liquid = accounts
      .filter(function (a) { return ["CASH", "BANK", "WALLET", "SAVINGS"].indexOf(String(a.type)) >= 0; })
      .reduce(function (sum, a) {
        return sum + AccountBalanceEngine.atDate(a, ledger, todayStamp());
      }, 0);
    var emMonths = burn3 > 0 ? liquid / burn3 : 0;

    // burn ratio = burn / income (lower is better)
    var burnRatio = income > 0 ? burn3 / income : 0;

    // debt to income
    var debtPayments = debtPaymentsMonthly(accounts, ledger, burnPeriods);
    var debtRatio = income > 0 ? debtPayments / income : 0;

    // net worth momentum: net worth now vs 6 months ago
    var nwNow = netWorthAt(accounts, ledger, todayStamp());
    var nw6m = netWorthAt(accounts, ledger, periodStart(prevPeriod(prevPeriod(curPeriod))));
    var momentum = nw6m !== 0 ? (nwNow - nw6m) / Math.abs(nw6m) : 0;

    // expense control: 1 - (expense/budget)
    var budgetRatio = budgetUsageRatio(accounts, ledger, curPeriod);
    var expenseControl = 1 - budgetRatio;

    var values = {
      SAVINGS_RATE: savingsRate,
      EMERGENCY_FUND_MONTHS: emMonths,
      BURN_RATE: burnRatio,
      DEBT_TO_INCOME: debtRatio,
      NET_WORTH_MOMENTUM: momentum,
      EXPENSE_CONTROL: expenseControl
    };

    // Write score rows (upsert by metric_code)
    ScoreService.METRICS.forEach(function (m) {
      var target = SettingsService.get(m.target) || 1;
      var current = values[m.code];
      var score = m.higherIsBetter
        ? Math.max(0, Math.min(100, Math.round((current / target) * 100)))
        : Math.max(0, Math.min(100, target > 0 ? Math.round((target / current) * 100) : 0));
      var status = score >= 80 ? "ON_TRACK" : score >= 50 ? "WARNING" : "FAIL";
      var row = findRow("financial_score", "metric_code", m.code);
      var rec = {
        metric_code: m.code,
        metric_name: m.name,
        weight: m.weight,
        current_value: current,
        target_value: target,
        score: score,
        status: status,
        remarks: ScoreService.remark(m, current, target, score),
        updated_at: isoNow()
      };
      if (row) {
        updateRow("financial_score", row, rec);
      } else {
        appendRow("financial_score", rec);
      }
    });
    return true;
  },

  remark: function (m, current, target, score) {
    if (score >= 80) return "Healthy. Keep this going.";
    if (score >= 50) return "Progressing but below target (" + target + ").";
    return "Needs attention. Current " + (Math.round(current * 100) / 100) +
           " vs target " + target + ".";
  }
};

function avgBurn(analytics, periods) {
  var total = 0, n = 0;
  periods.forEach(function (p) {
    for (var i = 0; i < analytics.length; i++) {
      if (String(analytics[i].period) === p && String(analytics[i].metric) === "EXPENSE" &&
          !analytics[i].dimension) { total += Number(analytics[i].value); n++; break; }
    }
  });
  return n > 0 ? total / n : 0;
}

function netWorthAt(accounts, ledger, date) {
  return accounts.reduce(function (sum, a) {
    return sum + AccountBalanceEngine.atDate(a, ledger, date);
  }, 0);
}

function debtPaymentsMonthly(accounts, ledger, periods) {
  var debtTypes = ["LOAN", "CREDIT_CARD"];
  var total = 0;
  periods.forEach(function (p) {
    var start = periodStart(p), end = periodEnd(p);
    accounts.forEach(function (a) {
      if (debtTypes.indexOf(String(a.type)) < 0) return;
      ledger.forEach(function (t) {
        if (String(t.date) >= start && String(t.date) <= end &&
            String(t.account_id) === String(a.account_id) &&
            String(t.type) === "EXPENSE") total += Number(t.amount);
      });
    });
  });
  return total / Math.max(periods.length, 1);
}

function budgetUsageRatio(accounts, ledger, period) {
  var budgets = readTable("budgets");
  var cats = readTable("categories");
  var totalBudget = 0, totalUsed = 0;
  cats.forEach(function (c) {
    var b = BudgetService.effective(c.category_id, period, budgets, cats);
    if (b <= 0) return;
    totalBudget += b;
    var used = ledger.reduce(function (sum, t) {
      return String(t.type) === "EXPENSE" && String(t.category_id) === String(c.category_id) &&
             String(t.date) >= periodStart(period) && String(t.date) <= periodEnd(period)
        ? sum + Number(t.amount) : sum;
    }, 0);
    totalUsed += used;
  });
  return totalBudget > 0 ? totalUsed / totalBudget : 0;
}

/**
 * Roadmap — financial progression engine.
 * Stages: SURVIVAL → EMERGENCY_FUND → DEBT_FREE → STABLE → GROWTH → INVESTMENT → FINANCIAL_FREEDOM
 */
var RoadmapService = {
  STAGES: [
    { name: "SURVIVAL", order: 1, desc: "Income covers expenses.", req: "income_gt_expense" },
    { name: "EMERGENCY_FUND", order: 2, desc: "Build an emergency fund covering 1-3 months.", req: "emergency_months" },
    { name: "DEBT_FREE", order: 3, desc: "Clear all non-mortgage debt.", req: "no_debt" },
    { name: "STABLE", order: 4, desc: "Savings rate above 10%.", req: "savings_rate" },
    { name: "GROWTH", order: 5, desc: "Net worth growing for 6+ months.", req: "growth" },
    { name: "INVESTMENT", order: 6, desc: "Invest 25%+ of net worth.", req: "invested_ratio" },
    { name: "FINANCIAL_FREEDOM", order: 7, desc: "Passive income covers expenses.", req: "passive_ratio" }
  ],

  update: function () {
    var ledger = readTable("transactions").filter(function (r) {
      return String(r.status).toUpperCase() === "POSTED";
    });
    var analytics = readTable("monthly_analytics");
    var accounts = readTable("accounts");
    var now = new Date();
    var curPeriod = monthStamp(now);

    var income = metric(analytics, curPeriod, "INCOME");
    var expense = metric(analytics, curPeriod, "EXPENSE");
    var savingsRate = income > 0 ? (income - expense) / income : 0;

    var burnPeriods = AnalyticsService.lastPeriods(Number(SettingsService.get("burn_rate_months")) || 3);
    var burn3 = avgBurn(analytics, burnPeriods);
    var liquid = accounts
      .filter(function (a) { return ["CASH", "BANK", "WALLET", "SAVINGS"].indexOf(String(a.type)) >= 0; })
      .reduce(function (s, a) { return s + AccountBalanceEngine.atDate(a, ledger, todayStamp()); }, 0);
    var emMonths = burn3 > 0 ? liquid / burn3 : 0;
    var emTarget = SettingsService.get("emergency_fund_months_target") || 3;

    var loans = accounts.filter(function (a) {
      return String(a.type) === "LOAN" || String(a.type) === "CREDIT_CARD";
    }).reduce(function (s, a) {
      return s + Math.abs(AccountBalanceEngine.atDate(a, ledger, todayStamp()));
    }, 0);

    var nwNow = netWorthAt(accounts, ledger, todayStamp());
    var nw6m = netWorthAt(accounts, ledger,
      periodStart(prevPeriod(prevPeriod(curPeriod))));
    var growth = nw6m !== 0 ? (nwNow - nw6m) / Math.abs(nw6m) : 0;

    var invested = accounts
      .filter(function (a) { return ["INVESTMENT", "CRYPTO"].indexOf(String(a.type)) >= 0; })
      .reduce(function (s, a) { return s + AccountBalanceEngine.atDate(a, ledger, todayStamp()); }, 0);
    var investedRatio = nwNow !== 0 ? invested / nwNow : 0;

    var passive = accounts
      .filter(function (a) { return String(a.type) === "INVESTMENT"; })
      .reduce(function (s, a) {
        return s + AccountBalanceEngine.atDate(a, ledger, todayStamp()) * 0.04 / 12; // 4% annual yield
      }, 0);
    var passiveRatio = expense > 0 ? passive / expense : 0;

    var reqs = {
      income_gt_expense: income > expense ? 100 : expense > 0 ? income / expense * 100 : 0,
      emergency_months: Math.min(100, (emMonths / emTarget) * 100),
      no_debt: loans === 0 ? 100 : Math.max(0, 100 - (loans / (nwNow || 1)) * 100),
      savings_rate: Math.min(100, (savingsRate / (SettingsService.get("savings_rate_target") || 0.1)) * 100),
      growth: Math.min(100, Math.max(0, growth * 1000)),
      invested_ratio: Math.min(100, (investedRatio / (Number(SettingsService.get("invested_ratio_target")) || 0.25)) * 100),
      passive_ratio: Math.min(100, (passiveRatio / 1) * 100)
    };

    var currentStage = 1;
    RoadmapService.STAGES.forEach(function (s, i) {
      var progress = reqs[s.req] || 0;
      if (progress >= 100) currentStage = Math.max(currentStage, s.order);
      var status = progress >= 100 ? "COMPLETED" : (s.order === currentStage ? "CURRENT" : "LOCKED");
      var row = findRow("roadmap", "stage_order", s.order);
      var rec = {
        stage_order: s.order,
        stage_name: s.name,
        description: s.desc,
        requirement_rule: s.req,
        status: status,
        progress: Math.round(progress * 100) / 100,
        recommendation: status === "COMPLETED" ? "Completed on " + todayStamp()
          : RoadmapService.recommendation(s, progress),
        achieved_date: status === "COMPLETED" ? todayStamp() : "",
        updated_at: isoNow()
      };
      // stage_id is the STG_... primary key. Only assign it on insert; on update
      // updateRow() preserves the existing value (it blanks explicitly-undefined
      // fields, which would otherwise wipe the key on every regeneration).
      if (!row) rec.stage_id = IdGenerator.stage();
      if (row) {
        updateRow("roadmap", row, rec);
      } else {
        appendRow("roadmap", rec);
      }
    });

    // persist current stage indicator on the dashboard metadata cell
    try { SettingsService.set("current_roadmap_stage", currentStage, "NUMBER"); } catch (e) {}
    return currentStage;
  },

  recommendation: function (stage, progress) {
    var tips = {
      SURVIVAL: "Focus on raising income or cutting fixed costs until income exceeds expenses.",
      EMERGENCY_FUND: "Set up an automatic monthly transfer to a savings account until 3 months of expenses are covered.",
      DEBT_FREE: "Apply the avalanche method: pay the highest-interest debt first while maintaining minimums.",
      STABLE: "Automate a 10%+ savings rate: pay yourself first on payday.",
      GROWTH: "Increase income streams and keep expense growth below income growth.",
      INVESTMENT: "Dollar-cost average into broad index funds monthly; target 25% of net worth invested.",
      FINANCIAL_FREEDOM: "Grow passive income until it fully covers monthly expenses."
    };
    if (progress >= 100) return "";
    return (tips[stage.name] || "Keep progressing.") +
      (progress > 0 ? " (" + Math.round(progress) + "% of requirement met)." : "");
  }
};

function metric(analytics, period, name) {
  for (var i = 0; i < analytics.length; i++) {
    if (String(analytics[i].period) === period && String(analytics[i].metric) === name &&
        !analytics[i].dimension) return Number(analytics[i].value);
  }
  return 0;
}

/**
 * Migration Service — export/import for portability to real databases.
 */
/** Tables a client may export/import via the migration API. */
var MIGRATION_ALLOW = [
  "transactions", "accounts", "categories", "income_sources",
  "budgets", "goals", "recurring"
];

/** Per-request import cap — keeps bulk restore within execution quotas. */
var MAX_IMPORT_ROWS = 1000;

/** Escapes a value for CSV export, neutralizing spreadsheet formula injection. */
function csvCell(v) {
  var s = String(v === undefined || v === null ? "" : v);
  if (/^[=+@]/.test(s)) s = "'" + s;
  return '"' + s.replace(/"/g, '""') + '"';
}

var MigrationService = {
  apiExport: function (body) {
    var table = body.table || "transactions";
    if (MIGRATION_ALLOW.indexOf(table) < 0) {
      throw new Error("Export not allowed for table '" + table + "'.");
    }
    var rows = readTable(table);
    var format = String(body.format || "json").toLowerCase();
    var def = TABLES[table];
    if (format === "csv") {
      var lines = [def.cols.join(",")];
      rows.forEach(function (r) {
        lines.push(def.cols.map(function (c) {
          return csvCell(r[c]);
        }).join(","));
      });
      return ContentService.createTextOutput(lines.join("\n"))
        .setMimeType(ContentService.MimeType.CSV);
    }
    return { data: rows };
  },

  apiImport: function (body) {
    if (!body.table || !body.rows) throw new Error("import requires 'table' and 'rows'.");
    if (MIGRATION_ALLOW.indexOf(body.table) < 0) {
      throw new Error("Import not allowed for table '" + body.table + "'.");
    }
    if (!Array.isArray(body.rows)) throw new Error("'rows' must be an array of records.");
    if (body.rows.length > MAX_IMPORT_ROWS) {
      throw new ValidationError([{ rule: "IMPORT_TOO_LARGE",
        message: "Import limited to " + MAX_IMPORT_ROWS + " rows per request." }]);
    }
    // Fail fast before writing anything: every row must be a plain record so a
    // malformed payload can never leave a partially-applied bulk import.
    body.rows.forEach(function (r, i) {
      if (!r || typeof r !== "object" || Array.isArray(r)) {
        throw new ValidationError([{ rule: "IMPORT_ROW_INVALID",
          message: "Row " + (i + 1) + " must be an object." }]);
      }
    });
    if (body.dry_run) return { data: { dry_run: true, would_insert: body.rows.length } };
    return withLock(function () {
      body.rows.forEach(function (r) { appendRow(body.table, r); });
      return { data: { inserted: body.rows.length } };
    });
  }
};
